
name: analysis
on:
  push:
    branches:
      - develop
      - stage
      - main
jobs:
  # Send to SonarQube
  analyze:
    name: Analyze Code
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'semantic-release') && !contains(github.event.head_commit.message, 'skip-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Project
        run: |
          poetry install
      - name: Run CI Tests
        run: |
          poetry run make sonar
      - name: Run Main Branch Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.branch.name=${{ github.branch }}
            -Dsonar.projectVersion=${{ github.RUN_NUMBER }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonar.megalus.io"
