name: tests
on:
  pull_request:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Ruff

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setups Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Install Project
        run: uv sync --dev
      - name: Run Ruff check
        run: uv run ruff check .
      - name: Run Ruff format check
        run: uv run ruff format --check .
  test:
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py_django:
          - python-version: "3.11"
            django-version: "5.0"
          - python-version: "3.11"
            django-version: "5.1"
          - python-version: "3.11"
            django-version: "5.2"
          - python-version: "3.12"
            django-version: "5.0"
          - python-version: "3.12"
            django-version: "5.1"
          - python-version: "3.12"
            django-version: "5.2"
          - python-version: "3.12"
            django-version: "6.0"
          - python-version: "3.13"
            django-version: "5.1"
          - python-version: "3.13"
            django-version: "5.2"
          - python-version: "3.13"
            django-version: "6.0"
          - python-version: "3.14"
            django-version: "6.0"
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.py_django.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py_django.python-version }}
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Install Project
        run: |
          uv sync --dev
          uv pip install "django==${{ matrix.py_django.django-version }}"
      - name: Run CI Tests
        env:
          PYTHONPATH: .
          STELA_ENV: test
        run: |
          uv run pytest -v -x -p no:warnings --cov-report term-missing --cov=.
